// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "earth":return img`
..............................
..............................
..............................
..............................
..............................
..............................
.............d1c..............
............db18b9............
..........d9688cccc...........
.........bd6888888c6..........
.........96688dbbcbc..........
.........96668bdbbccb.........
........99668bdbbbc8c.........
........bd6688bbbbcc8.........
........bc9688dbbbcc8.........
........bc96888bbbcc8.........
........bcc68888bcc88.........
........9cc68888bcc88.........
.........c6688888bcb8.........
.........c6688888cc88.........
.........c9668888888..........
..........c9d88888b...........
............681888............
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
            case "image2":
            case "tree":return img`
. . . . . . . . . . 
. . . 7 8 6 7 7 . . 
. . 6 7 6 6 7 8 . . 
. 6 7 6 7 6 6 7 7 . 
. 7 7 7 6 7 6 7 7 . 
. 6 6 7 6 7 7 6 7 . 
. 8 7 7 6 6 6 7 6 . 
. 6 8 6 6 6 7 7 6 . 
. . 6 6 6 7 6 6 6 . 
. . . 8 6 6 6 6 8 . 
. . . . e e e . . . 
. . . . . e . . . . 
. . . . . e . . . . 
. . . . . e . . . . 
. . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
